/*
Culture enum file
12/7/2023
Kate Stenberg
 */

public enum Culture {NORTHAMERICAN, MESOAMERICAN, EUROPEAN, SLAVIC, EASTASIAN, INDIAN, MIDDLEEASTERN, AFRICAN, AUSTRONESIAN, CELTIC, POLYNESIAN, SCANDINAVIAN}
