/*
FINAL PROJECT
Occupation enum file
12/7/2023
Kate Stenberg
 */

public enum Occupation {TELEVISION, NOBILITY, SCIENCE, CELEBRITY, JOURNALIST, CHEF, CORPORATE, STUDENT, PARENTGUARDIAN, OFFICE, TRADE, SMALLBUSINESS, HEALTHCARE, MAGE, CHILD, IDLE, SOCIALITE, WAR, POLITICS, LABOR, HOSPITALITY, COVERT, PUBLICSERVICE, LAW, ACADEMIC, CREATIVE, OTHER, EDUCATION, ROYAL, ATHLETE, POLICE, SERVANT, CRIME, PIRATE, HUNTER, SOLDIER, RETAIL, FINANCE, MULTIPLE, BOOKS}
