/*
FINAL PROJECT
RaceType enum file
12/7/2023
Kate Stenberg
 */

public enum RaceType {ANGELS, ELVES, DWARVES, GOBLINS, ORCS, FAE, VAMPIRES, GODS, WEREWOLVES, MERFOLK, SHAPESHIFTERS, DEMIGODS, WITCHES, MAGES}
