/*
FINAL PROJECT
TropeType enum file
12/7/2023
Kate Stenberg
 */

public enum TropeType {AGEGAP, BOSSEMPLOYEE, COWORKERS, CLASSDIFFERENCE, GRUMPYSUNSHINE, ARRANGEDMARRIAGE, FAKERELATIONSHIP, FATEDMATES, FORBIDDEN, FORCEDPROXIMITY, FRIENDSTOLOVERS, ENEMIESTOLOVERS, FWB, INSTALOVE, SLOWBURN, MARRIAGEOFCONVENIENCE, LOVETRIANGLE, SECONDCHANCES, SECRETRELATIONSHIP, SIBLINGSSBESTFRIEND, PINING, LOVE}
